# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DisplayImage = QtWidgets.QLabel(self.centralwidget)
        self.DisplayImage.setGeometry(QtCore.QRect(20, 100, 841, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DisplayImage.setFont(font)
        self.DisplayImage.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.DisplayImage.setAlignment(QtCore.Qt.AlignCenter)
        self.DisplayImage.setObjectName("DisplayImage")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(900, 240, 311, 451))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.widget = QtWidgets.QWidget(self.frame_5)
        self.widget.setGeometry(QtCore.QRect(12, 12, 261, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.blur_slider = QtWidgets.QSlider(self.widget)
        self.blur_slider.setMinimum(0)
        self.blur_slider.setMaximum(5)
        self.blur_slider.setSingleStep(1)
        self.blur_slider.setPageStep(1)
        self.blur_slider.setProperty("value", 0)
        self.blur_slider.setTracking(True)
        self.blur_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blur_slider.setInvertedAppearance(False)
        self.blur_slider.setInvertedControls(False)
        self.blur_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.blur_slider.setTickInterval(1)
        self.blur_slider.setObjectName("blur_slider")
        self.verticalLayout_3.addWidget(self.blur_slider)
        self.splitter_4 = QtWidgets.QSplitter(self.widget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_19 = QtWidgets.QLabel(self.splitter_4)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.splitter_4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.splitter_4)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.splitter_4)
        self.widget_2 = QtWidgets.QWidget(self.frame_5)
        self.widget_2.setGeometry(QtCore.QRect(10, 140, 261, 121))
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(11, 11, 219, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gamma_slider = QtWidgets.QSlider(self.widget_2)
        self.gamma_slider.setGeometry(QtCore.QRect(10, 51, 241, 16))
        self.gamma_slider.setMinimum(0)
        self.gamma_slider.setMaximum(20)
        self.gamma_slider.setSingleStep(1)
        self.gamma_slider.setPageStep(1)
        self.gamma_slider.setProperty("value", 10)
        self.gamma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gamma_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gamma_slider.setTickInterval(1)
        self.gamma_slider.setObjectName("gamma_slider")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setGeometry(QtCore.QRect(10, 70, 241, 16))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.splitter_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.widget_3 = QtWidgets.QWidget(self.frame_5)
        self.widget_3.setGeometry(QtCore.QRect(12, 284, 271, 131))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.sharpen_slider = QtWidgets.QSlider(self.widget_3)
        self.sharpen_slider.setMinimum(1)
        self.sharpen_slider.setMaximum(5)
        self.sharpen_slider.setSingleStep(1)
        self.sharpen_slider.setPageStep(1)
        self.sharpen_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpen_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sharpen_slider.setTickInterval(1)
        self.sharpen_slider.setObjectName("sharpen_slider")
        self.verticalLayout_6.addWidget(self.sharpen_slider)
        self.splitter_3 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_16 = QtWidgets.QLabel(self.splitter_3)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.splitter_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.splitter_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.splitter_3)
        self.SaveImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImageBtn.setGeometry(QtCore.QRect(762, 680, 101, 31))
        self.SaveImageBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.SaveImageBtn.setObjectName("SaveImageBtn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 1231, 41))
        self.frame.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(110, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.ConsoleDisplay = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleDisplay.setGeometry(QtCore.QRect(20, 680, 731, 31))
        self.ConsoleDisplay.setStyleSheet("background-color: rgb(255, 255, 255);\n"
" border: 1px solid grey;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 127);")
        self.ConsoleDisplay.setObjectName("ConsoleDisplay")
        self.UndoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.UndoBtn.setGeometry(QtCore.QRect(20, 60, 98, 31))
        self.UndoBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.UndoBtn.setObjectName("UndoBtn")
        self.UndoAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.UndoAllBtn.setGeometry(QtCore.QRect(125, 60, 97, 31))
        self.UndoAllBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.UndoAllBtn.setObjectName("UndoAllBtn")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(890, 100, 321, 131))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.EqualisationBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EqualisationBtn.setFont(font)
        self.EqualisationBtn.setObjectName("EqualisationBtn")
        self.LogTransformBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogTransformBtn.setFont(font)
        self.LogTransformBtn.setObjectName("LogTransformBtn")
        self.InvertBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InvertBtn.setFont(font)
        self.InvertBtn.setObjectName("InvertBtn")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(580, 60, 281, 31))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.Browse = QtWidgets.QPushButton(self.splitter_5)
        self.Browse.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.Browse.setObjectName("Browse")
        self.CameraBtn = QtWidgets.QPushButton(self.splitter_5)
        self.CameraBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.CameraBtn.setObjectName("CameraBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.action_UndoAll = QtWidgets.QAction(MainWindow)
        self.action_UndoAll.setObjectName("action_UndoAll")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.action_SaveAndExit = QtWidgets.QAction(MainWindow)
        self.action_SaveAndExit.setObjectName("action_SaveAndExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DisplayImage.setText(_translate("MainWindow", "No image loaded"))
        self.label_3.setText(_translate("MainWindow", "Blur"))
        self.label_19.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "1"))
        self.label_21.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "Gamma Correction"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "Sharpening"))
        self.label_16.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "5"))
        self.SaveImageBtn.setText(_translate("MainWindow", "Save Image"))
        self.label_14.setText(_translate("MainWindow", "ImaqArt"))
        self.label_15.setText(_translate("MainWindow", "(Basic Image Editor)"))
        self.ConsoleDisplay.setText(_translate("MainWindow", "No operation performed yet!"))
        self.UndoBtn.setText(_translate("MainWindow", "Undo"))
        self.UndoAllBtn.setText(_translate("MainWindow", "Undo All"))
        self.EqualisationBtn.setText(_translate("MainWindow", "Apply Histogram Equalisation"))
        self.LogTransformBtn.setText(_translate("MainWindow", "Apply Log Transformation"))
        self.InvertBtn.setText(_translate("MainWindow", "Invert Image"))
        self.Browse.setText(_translate("MainWindow", "Browse Image"))
        self.CameraBtn.setText(_translate("MainWindow", "Capture"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "&Open&"))
        self.actionSave.setText(_translate("MainWindow", "&Save&"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo&"))
        self.action_UndoAll.setText(_translate("MainWindow", "&UndoAll&"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.action_SaveAndExit.setText(_translate("MainWindow", "&SaveAndExit&"))

